# Generated by Django 3.2.15 on 2022-09-14 13:42

from django.db import migrations, models
import django_db_cascade.deletions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('start_time', models.DateTimeField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('conversation', models.ForeignKey(on_delete=django_db_cascade.deletions.DB_CASCADE, to='chatbot.conversation')),
            ],
        ),
    ]
