# Generated by Django 3.2.15 on 2022-09-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
