# Generated by Django 3.2.15 on 2022-09-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_auto_20220914_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='location_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
