# Generated by Django 3.2.15 on 2022-09-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_alter_message_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='weather_request_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='weather_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
